# Generated by Django 4.2.5 on 2023-10-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('science_degree', models.CharField(max_length=100)),
                ('books', models.TextField(blank=True, null=True)),
                ('works', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
