# Generated by Django 4.2.5 on 2023-10-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('faculty', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('research_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_fields.researchfield')),
            ],
        ),
    ]
