# Generated by Django 4.2.5 on 2023-10-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('course', models.CharField(choices=[('B', 'Бакалавриат'), ('S', 'Специалитет'), ('M', 'Магистратура')], max_length=1)),
                ('study_group', models.CharField(max_length=10)),
            ],
        ),
    ]
